blog/urls.py
from django.urls import path
from .views import blog_view, blog_single, blog_search #,blog_category
from blog.feeds import LatestEntriesFeed

app_name = 'blog'

urlpatterns = [
    path('', blog_view, name='index'),
    path('<int:pid>', blog_single, name='single'),
    path('author/<author_username>', blog_view, name='author'),
    path('search/', blog_search, name='search'),
    path('tag/<str:tag_name>', blog_view, name='tag'),
    path("rss/feed/", LatestEntriesFeed()),
    path('category/<str:category_name>', blog_view, name='category'),
]

django_website_example/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from blog.sitemaps import BlogSitemap
from django.contrib.sitemaps.views import sitemap
from testing.sitemaps import StaticViewSitemap
from debug_toolbar.toolbar import debug_toolbar_urls

sitemaps = {
    'static': StaticViewSitemap,
    'blog': BlogSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('testing.urls')),
    path('accounts/', include('accounts.urls')),
    path('blog/', include('blog.urls')),
    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
    path('robots.txt', include('robots.urls')),
    path('tinymce/', include('tinymce.urls')),
    path('captcha/', include('captcha.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += debug_toolbar_urls()

testing/urls.py
from django.urls import path
from testing.views import index_view, about_view, contact_view, form_test_view, newsletter_view


app_name = 'testing'

urlpatterns = [
    path('', index_view, name='index'),
    path('about', about_view, name='about'),
    path('contact', contact_view, name='contact'),
    path('form-test', form_test_view, name='form-test'),
    path('newsletter', newsletter_view, name='newsletter'),
    ]

testing/models.py
from django.db import models

# Create your models here.

class Contact(models.Model):
    name = models.CharField(max_length=150)
    email = models.EmailField()
    subject = models.CharField(max_length=200, default=None, blank=True)
    message = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    class Meta:
        ordering = ['-created_date']
    
    def __str__(self):
        return f'{self.name} - {self.subject}'
    
class Newsletter(models.Model):
    email = models.EmailField()
    created_date = models.DateTimeField(auto_now_add=True)
    class Meta:
        ordering = ['-created_date']

    def __str__(self):
        return self.email

testing/forms.py
from django import forms
from testing.models import Contact, Newsletter
from captcha.fields import CaptchaField


class ContactForm(forms.ModelForm):
    captcha = CaptchaField()
    class Meta:
        model = Contact
        fields = '__all__'
    

class TestForm(forms.ModelForm):
    name = forms.CharField(max_length=150)
    email = forms.EmailField()
    subject = forms.CharField(max_length=200)
    message = forms.CharField(widget=forms.Textarea)
    
    
class NewsletterForm(forms.ModelForm):
    class Meta:
        model = Newsletter
        fields = '__all__'

testing/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from testing.forms import ContactForm, NewsletterForm
from django.contrib import messages

def index_view(request):
    return render(request, 'testing/index.html')


def about_view(request):
    return render(request, 'testing/about.html')


def contact_view(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            new_instance = form.save(commit=False)
            new_instance.name = 'Anonymous'
            new_instance.save()
            form.save()
            human = True
            messages.add_message(request, messages.SUCCESS, 'Your message has been sent')
        elif form.errors:
            messages.add_message(request, messages.ERROR, 'Your message has not been sent, check your input')
    form = ContactForm()
    return render(request, 'testing/contact.html', {'form':form})


def form_test_view(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponse('Form submitted successfully')
        else:
            return HttpResponse('Form is not valid')
    else:
        form = ContactForm()
    return render(request, 'testing/form-test.html', {'form':form})


def newsletter_view(request):
    if request.method == 'POST':
        form = NewsletterForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/')
    else:
        return HttpResponseRedirect('/')

templates/testing/about.html
{% extends 'base.html' %} {% block content %} {% load static %}

<!-- start banner Area -->
<section class="about-banner relative">
  <div class="overlay overlay-bg"></div>
  <div class="container">
    <div class="row d-flex align-items-center justify-content-center">
      <div class="about-content col-lg-12">
        <h1 class="text-white">About Us</h1>
        <p class="text-white link-nav">
          <a href="index.html">Home </a>
          <span class="lnr lnr-arrow-right"></span>
          <a href="about.html"> About Us</a>
        </p>
      </div>
    </div>
  </div>
</section>
<!-- End banner Area -->

<!-- Start about-info Area -->
<section class="about-info-area section-gap">
  <div class="container">
    <div class="row align-items-center">
      <div class="col-lg-6 info-left">
        <img class="img-fluid" src="{% static 'img/about/info-img.jpg' %}" alt="" />
      </div>
      <div class="col-lg-6 info-right">
        <h6>About Us</h6>
        <h1>Who We Are?</h1>
        <p>
          Here, I focus on a range of items and features that we use in life
          without giving them a second thought. such as Coca Cola. Dolor sit
          amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt
          ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis
          nostrud exercitation ullamco.
        </p>
      </div>
    </div>
  </div>
</section>
<!-- End about-info Area -->

<!-- Start other-issue Area -->
<section class="other-issue-area section-gap">
  <div class="container">
    <div class="row d-flex justify-content-center">
      <div class="menu-content pb-70 col-lg-9">
        <div class="title text-center">
          <h1 class="mb-10">Other issues we can help you with</h1>
          <p>
            We all live in an age that belongs to the young at heart. Life that
            is.
          </p>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-3 col-md-6">
        <div class="single-other-issue">
          <div class="thumb">
            <img class="img-fluid" src="{% static 'img/o1.jpg' %}" alt="" />
          </div>
          <a href="#">
            <h4>Rent a Car</h4>
          </a>
          <p>
            The preservation of human life is the ultimate value, a pillar of
            ethics and the foundation.
          </p>
        </div>
      </div>
      <div class="col-lg-3 col-md-6">
        <div class="single-other-issue">
          <div class="thumb">
            <img class="img-fluid" src="{% static 'img/o2.jpg' %}" alt="" />
          </div>
          <a href="#">
            <h4>Cruise Booking</h4>
          </a>
          <p>
            I was always somebody who felt quite sorry for myself, what I had
            not got compared.
          </p>
        </div>
      </div>
      <div class="col-lg-3 col-md-6">
        <div class="single-other-issue">
          <div class="thumb">
            <img class="img-fluid" src="{% static 'img/o3.jpg' %}" alt="" />
          </div>
          <a href="#">
            <h4>To Do List</h4>
          </a>
          <p>
            The following article covers a topic that has recently moved to
            center stage–at least it seems.
          </p>
        </div>
      </div>
      <div class="col-lg-3 col-md-6">
        <div class="single-other-issue">
          <div class="thumb">
            <img class="img-fluid" src="{% static 'img/o4.jpg' %}" alt="" />
          </div>
          <a href="#">
            <h4>Food Features</h4>
          </a>
          <p>
            There are many kinds of narratives and organizing principles.
            Science is driven by evidence.
          </p>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- End other-issue Area -->
{% endblock content %}

templates/testing/contact.html
{% extends 'base.html' %} {% block content %} {% load static %}
<!-- start banner Area -->
<section class="relative about-banner">
  <div class="overlay overlay-bg"></div>
  <div class="container">
    <div class="row d-flex align-items-center justify-content-center">
      <div class="about-content col-lg-12">
        <h1 class="text-white">Contact Us</h1>
        <p class="text-white link-nav">
          <a href="index.html">Home </a>
          <span class="lnr lnr-arrow-right"></span>
          <a href="contact.html"> Contact Us</a>
        </p>
      </div>
    </div>
  </div>
</section>
<!-- End banner Area -->

<!-- Start contact-page Area -->
<section class="contact-page-area section-gap">
  <div class="container">
    <div class="row">
      <div class="map-wrap" style="width: 100%; height: 445px" id="map"></div>
      <div class="col-lg-4 d-flex flex-column address-wrap">
        <div class="single-contact-address d-flex flex-row">
          <div class="icon">
            <span class="lnr lnr-home"></span>
          </div>
          <div class="contact-details">
            <h5>Binghamton, New York</h5>
            <p>4343 Hinkle Deegan Lake Road</p>
          </div>
        </div>
        <div class="single-contact-address d-flex flex-row">
          <div class="icon">
            <span class="lnr lnr-phone-handset"></span>
          </div>
          <div class="contact-details">
            <h5>00 (958) 9865 562</h5>
            <p>Mon to Fri 9am to 6 pm</p>
          </div>
        </div>
        <div class="single-contact-address d-flex flex-row">
          <div class="icon">
            <span class="lnr lnr-envelope"></span>
          </div>
          <div class="contact-details">
            <h5>support@colorlib.com</h5>
            <p>Send us your query anytime!</p>
          </div>
        </div>
      </div>
      <div class="col-lg-8">
        <form
          class="form-area contact-form text-right"
          action="{% url 'testing:contact' %}"
          method="post"
        >
          {% csrf_token %}
          <div class="row">
            
            <div class="col-lg-6 form-group">
              <input
                name="name"
                placeholder="Enter your name"
                onfocus="this.placeholder = ''"
                onblur="this.placeholder = 'Enter your name'"
                class="common-input mb-20 form-control"
                required=""
                type="text"
              />

              <input
                name="email"
                placeholder="Enter email address"
                pattern="[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{1,63}$"
                onfocus="this.placeholder = ''"
                onblur="this.placeholder = 'Enter email address'"
                class="common-input mb-20 form-control"
                required=""
                type="email"
              />

              <input
                name="subject"
                placeholder="Enter subject"
                onfocus="this.placeholder = ''"
                onblur="this.placeholder = 'Enter subject'"
                class="common-input mb-20 form-control"
                type="text"
              />
            </div>
            <div class="col-lg-6 form-group">
              <textarea
                class="common-textarea form-control"
                name="message"
                placeholder="Enter Messege"
                onfocus="this.placeholder = ''"
                onblur="this.placeholder = 'Enter Messege'"
                required=""
              ></textarea>
            </div>
            
             
            <div class="col-lg-12">
              <div  class="col-lg-14 pb-3">
                {{ form.captcha }}
              </div>
              <div class="alert-msg" style="text-align: left"></div>
              <button class="genric-btn primary" style="float: right" type="submit">
                Send Message
              </button>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</section>
<!-- End contact-page Area -->

{% endblock content %}

templates/testing/form-test.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Form Test</title>
  </head>
  <body>
    <h3>Form Test</h3>
    <form action="{% url 'testing:form-test' %}" method="POST">
      {% csrf_token %} {{ form.as_p }}
      <p>
        <button type="submit">Submit</button>
      </p>
    </form>
  </body>
</html>

templates/testing/index-recent-posts.html
{% load static %}

{% for post in posts %}
<div class="single-recent-blog-post item">
    <div class="thumb">
      <img class="img-fluid" src="{{ post.image.url }}" alt="" />
    </div>
    <div class="details">
      <div class="tags">
        <ul>
            {% for category in post.category.all %}
            <li><a href="{% url 'blog:category' category_name=category.name %}">{{ category }}</a></li>
            {% endfor %}
        </ul>
      </div>
      <a href="{% url 'blog:single' pid=post.id %}"><h4 class="title">{{ post.title }}</h4></a>
      <p>
        {{ post.content|truncatewords:5 }}
      </p>
      <h6 class="date">{{ post.published_date|date:"d M Y"}}</h6>
    </div>
  </div>
{% endfor %}

templates/testing/index.html
{% extends 'base.html' %} {% block content %} {% load static %} {% load index_tags %}

<!-- start banner Area -->
<section class="banner-area relative">
  <div class="overlay overlay-bg"></div>
  <div class="container">
    <div class="row fullscreen align-items-center justify-content-between">
      <div class="col-lg-6 col-md-6 banner-left">
        <h6 class="text-white">Away from monotonous life</h6>
        <h1 class="text-white">Magical Travel</h1>
        <p class="text-white">
          If you are looking at blank cassettes on the web, you may be very
          confused at the difference in price. You may see some for as low as
          $.17 each.
        </p>
      </div>
    </div>
  </div>
</section>
<!-- End banner Area -->

<!-- Start popular-destination Area -->
<section class="popular-destination-area section-gap">
  <div class="container">
    <div class="row d-flex justify-content-center">
      <div class="menu-content pb-70 col-lg-8">
        <div class="title text-center">
          <h1 class="mb-10">Popular Destinations</h1>
          <p>
            We all live in an age that belongs to the young at heart. Life that
            is becoming extremely fast, day.
          </p>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-4">
        <div class="single-destination relative">
          <div class="thumb relative">
            <div class="overlay overlay-bg"></div>
            <img class="img-fluid" src="{% static 'img/d1.jpg' %}" alt="" />
          </div>
          <div class="desc">
            <a href="#" class="price-btn">$150</a>
            <h4>Mountain River</h4>
            <p>Paraguay</p>
          </div>
        </div>
      </div>
      <div class="col-lg-4">
        <div class="single-destination relative">
          <div class="thumb relative">
            <div class="overlay overlay-bg"></div>
            <img class="img-fluid" src="{% static 'img/d2.jpg' %}" alt="" />
          </div>
          <div class="desc">
            <a href="#" class="price-btn">$250</a>
            <h4>Dream City</h4>
            <p>Paris</p>
          </div>
        </div>
      </div>
      <div class="col-lg-4">
        <div class="single-destination relative">
          <div class="thumb relative">
            <div class="overlay overlay-bg"></div>
            <img class="img-fluid" src="{% static 'img/d3.jpg' %}" alt="" />
          </div>
          <div class="desc">
            <a href="#" class="price-btn">$350</a>
            <h4>Cloud Mountain</h4>
            <p>Sri Lanka</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- End popular-destination Area -->

<!-- Start other-issue Area -->
<section class="other-issue-area section-gap">
  <div class="container">
    <div class="row d-flex justify-content-center">
      <div class="menu-content pb-70 col-lg-9">
        <div class="title text-center">
          <h1 class="mb-10">Other issues we can help you with</h1>
          <p>
            We all live in an age that belongs to the young at heart. Life that
            is.
          </p>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-3 col-md-6">
        <div class="single-other-issue">
          <div class="thumb">
            <img class="img-fluid" src="{% static 'img/o1.jpg' %}" alt="" />
          </div>
          <a href="#">
            <h4>Rent a Car</h4>
          </a>
          <p>
            The preservation of human life is the ultimate value, a pillar of
            ethics and the foundation.
          </p>
        </div>
      </div>
      <div class="col-lg-3 col-md-6">
        <div class="single-other-issue">
          <div class="thumb">
            <img class="img-fluid" src="{% static 'img/o2.jpg' %}" alt="" />
          </div>
          <a href="#">
            <h4>Cruise Booking</h4>
          </a>
          <p>
            I was always somebody who felt quite sorry for myself, what I had
            not got compared.
          </p>
        </div>
      </div>
      <div class="col-lg-3 col-md-6">
        <div class="single-other-issue">
          <div class="thumb">
            <img class="img-fluid" src="{% static 'img/o3.jpg' %}" alt="" />
          </div>
          <a href="#">
            <h4>To Do List</h4>
          </a>
          <p>
            The following article covers a topic that has recently moved to
            center stage–at least it seems.
          </p>
        </div>
      </div>
      <div class="col-lg-3 col-md-6">
        <div class="single-other-issue">
          <div class="thumb">
            <img class="img-fluid" src="{% static 'img/o4.jpg' %}" alt="" />
          </div>
          <a href="#">
            <h4>Food Features</h4>
          </a>
          <p>
            There are many kinds of narratives and organizing principles.
            Science is driven by evidence.
          </p>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- End other-issue Area -->

<!-- Start home-about Area -->
<section class="home-about-area">
  <div class="container-fluid">
    <div class="row align-items-center justify-content-end">
      <div class="col-lg-6 col-md-12 home-about-left">
        <h1>
          Did not find your Package? <br />
          Feel free to ask us. <br />
          We‘ll make it for you
        </h1>
        <p>
          inappropriate behavior is often laughed off as “boys will be boys,”
          women face higher conduct standards especially in the workplace.
          That’s why it’s crucial that, as women, our behavior on the job is
          beyond reproach. inappropriate behavior is often laughed.
        </p>
        <a href="#" class="primary-btn text-uppercase">request custom price</a>
      </div>
      <div class="col-lg-6 col-md-12 home-about-right no-padding">
        <img class="img-fluid" src="{% static 'img/about-img.jpg' %}" alt="" />
      </div>
    </div>
  </div>
</section>
<!-- End home-about Area -->

<!-- Start blog Area -->
<section class="recent-blog-area section-gap">
  <div class="container">
    <div class="row d-flex justify-content-center">
      <div class="menu-content pb-60 col-lg-9">
        <div class="title text-center">
          <h1 class="mb-10">Latest from Our Blog</h1>
          <p>
            With the exception of Nietzsche, no other madman has contributed so
            much to human sanity as has.
          </p>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="active-recent-blog-carusel">
        {% index_posts %}
        {% comment %}
        <div class="single-recent-blog-post item">
          <div class="thumb">
            <img class="img-fluid" src="{% static 'img/b1.jpg' %}" alt="" />
          </div>
          <div class="details">
            <div class="tags">
              <ul>
                <li>
                  <a href="#">Travel</a>
                </li>
                <li>
                  <a href="#">Life Style</a>
                </li>
              </ul>
            </div>
            <a href="#"><h4 class="title">Low Cost Advertising</h4></a>
            <p>
              Acres of Diamonds… you’ve read the famous story, or at least had
              it related to you. A farmer.
            </p>
            <h6 class="date">31st January,2018</h6>
          </div>
        </div>
         <div class="single-recent-blog-post item">
          <div class="thumb">
            <img class="img-fluid" src="{% static 'img/b2.jpg' %}" alt="" />
          </div>
          <div class="details">
            <div class="tags">
              <ul>
                <li>
                  <a href="#">Travel</a>
                </li>
                <li>
                  <a href="#">Life Style</a>
                </li>
              </ul>
            </div>
            <a href="#"><h4 class="title">Creative Outdoor Ads</h4></a>
            <p>
              Acres of Diamonds… you’ve read the famous story, or at least had
              it related to you. A farmer.
            </p>
            <h6 class="date">31st January,2018</h6>
          </div>
        </div>
        <div class="single-recent-blog-post item">
          <div class="thumb">
            <img class="img-fluid" src="{% static 'img/b3.jpg' %}" alt="" />
          </div>
          <div class="details">
            <div class="tags">
              <ul>
                <li>
                  <a href="#">Travel</a>
                </li>
                <li>
                  <a href="#">Life Style</a>
                </li>
              </ul>
            </div>
            <a href="#"
              ><h4 class="title">It's Classified How To Utilize Free</h4></a
            >
            <p>
              Acres of Diamonds… you’ve read the famous story, or at least had
              it related to you. A farmer.
            </p>
            <h6 class="date">31st January,2018</h6>
          </div>
        </div>
        <div class="single-recent-blog-post item">
          <div class="thumb">
            <img class="img-fluid" src="{% static 'img/b1.jpg' %}" alt="" />
          </div>
          <div class="details">
            <div class="tags">
              <ul>
                <li>
                  <a href="#">Travel</a>
                </li>
                <li>
                  <a href="#">Life Style</a>
                </li>
              </ul>
            </div>
            <a href="#"><h4 class="title">Low Cost Advertising</h4></a>
            <p>
              Acres of Diamonds… you’ve read the famous story, or at least had
              it related to you. A farmer.
            </p>
            <h6 class="date">31st January,2018</h6>
          </div>
        </div>
        <div class="single-recent-blog-post item">
          <div class="thumb">
            <img class="img-fluid" src="{% static 'img/b2.jpg' %}" alt="" />
          </div>
          <div class="details">
            <div class="tags">
              <ul>
                <li>
                  <a href="#">Travel</a>
                </li>
                <li>
                  <a href="#">Life Style</a>
                </li>
              </ul>
            </div>
            <a href="#"><h4 class="title">Creative Outdoor Ads</h4></a>
            <p>
              Acres of Diamonds… you’ve read the famous story, or at least had
              it related to you. A farmer.
            </p>
            <h6 class="date">31st January,2018</h6>
          </div>
        </div>
        <div class="single-recent-blog-post item">
          <div class="thumb">
            <img class="img-fluid" src="{% static 'img/b3.jpg' %}" alt="" />
          </div>
          <div class="details">
            <div class="tags">
              <ul>
                <li>
                  <a href="#">Travel</a>
                </li>
                <li>
                  <a href="#">Life Style</a>
                </li>
              </ul>
            </div>
            <a href="#"
              ><h4 class="title">It's Classified How To Utilize Free</h4></a
            >
            <p>
              Acres of Diamonds… you’ve read the famous story, or at least had
              it related to you. A farmer.
            </p>
            <h6 class="date">31st January,2018</h6>
          </div>
        </div> {% endcomment %}
      </div>
    </div>
  </div>
</section>
<!-- End recent-blog Area -->

{% endblock content %}