blog/urls.py
from django.urls import path
from .views import blog_view, blog_single, blog_search #,blog_category
from blog.feeds import LatestEntriesFeed

app_name = 'blog'

urlpatterns = [
    path('', blog_view, name='index'),
    path('<int:pid>', blog_single, name='single'),
    path('author/<author_username>', blog_view, name='author'),
    path('search/', blog_search, name='search'),
    path('tag/<str:tag_name>', blog_view, name='tag'),
    path("rss/feed/", LatestEntriesFeed()),
    path('category/<str:category_name>', blog_view, name='category'),
]

django_website_example/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from blog.sitemaps import BlogSitemap
from django.contrib.sitemaps.views import sitemap
from testing.sitemaps import StaticViewSitemap
from debug_toolbar.toolbar import debug_toolbar_urls

sitemaps = {
    'static': StaticViewSitemap,
    'blog': BlogSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('testing.urls')),
    path('accounts/', include('accounts.urls')),
    path('blog/', include('blog.urls')),
    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
    path('robots.txt', include('robots.urls')),
    path('tinymce/', include('tinymce.urls')),
    path('captcha/', include('captcha.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += debug_toolbar_urls()

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from taggit.managers import TaggableManager
from tinymce import models as tinymce_models
# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=255)
    class Meta:
        ordering = ['name']

    def __str__(self):
        return f'{self.name}'
    
    
class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    title = models.CharField(max_length=150)
    content = tinymce_models.HTMLField()
    category = models.ManyToManyField(Category)
    tag = TaggableManager()
    image = models.ImageField(upload_to='blog/', default='blog/default.jpg')
    counted_views = models.IntegerField(default=0)
    login_required = models.BooleanField(default=False)
    status = models.BooleanField(default=False)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    published_date = models.DateTimeField(null=True)
    class Meta:
        ordering = ['created_date']
    
    def __str__(self):
        return f'{self.title} - {self.id}'

    def get_absolute_url(self):
        from django.urls import reverse
        return reverse("blog:single", kwargs={"pid": self.id})

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    name = models.CharField(max_length=255, blank=False)
    email = models.EmailField(blank=False)
    subject = models.CharField(max_length=255, blank=True, default='No Subject')
    message = models.TextField(blank=False)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    approved = models.BooleanField(default=False)

    class Meta:
        ordering = ['created_date']

    def __str__(self):
        return f'{self.name} - {self.post}'

blog/forms.py
from django import forms
from blog.models import Comment
from captcha.fields import CaptchaField

class CommentForm(forms.ModelForm):
    # captcha = CaptchaField()
    class Meta:
        model = Comment
        fields = ['name', 'email', 'subject', 'message']

blog/views.py
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect
from blog.models import Post, Comment
from django.utils import timezone
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from blog.forms import CommentForm
from django.urls import reverse

# Create your views here.

def blog_view(request, category_name=None, author_username=None, tag_name=None):
    posts = Post.objects.filter(published_date__lte=timezone.now(), status=1)
    if category_name:
        posts = posts.filter(category__name=category_name)
    if author_username:
        posts = posts.filter(author__username=author_username)
    if tag_name:
        posts = posts.filter(tag__name=tag_name)
    posts = Paginator(posts, 3)
    try:
        page_number = request.GET.get('page')
        posts = posts.get_page(page_number)
    except PageNotAnInteger:
        posts = posts.get_page(1)
    except EmptyPage:
        posts = posts.get_page(1)
    context = {
        'posts': posts
    }
    return render(request, 'blog/blog-home.html', context)


def blog_single(request,pid):
    post = get_object_or_404(Post, id=pid, status=1, published_date__lte=timezone.now())
    post.counted_views += 1
    post.save()
    other_posts = Post.objects.filter(published_date__lte=timezone.now(), status=1).exclude(id=pid)
    comment = Comment.objects.filter(post=post.id, approved=True).order_by('-created_date')
    if request.method == 'POST':
        from django.contrib import messages
        form = CommentForm(request.POST)
        if form.is_valid():
            new_instance = form.save(commit=False)
            if new_instance.subject == '':
                new_instance.subject = 'No subject'
            new_instance.post = post
            new_instance.save()
            form.save()
            messages.add_message(request, messages.SUCCESS, 'Your comment has been submitted and is awaiting approval')
        elif form.errors:
            messages.add_message(request, messages.ERROR, 'Your comment didnt go through, check your input')
    form = CommentForm()
    context={
        'post': post,
        'next': other_posts.filter(id__gt=post.id).order_by('id').first(),
        'previous': other_posts.filter(id__lt=post.id).order_by('-id').first(),
        'comments': comment,
        'form': form,
    }
    if post.login_required and not request.user.is_authenticated:
            return HttpResponseRedirect(reverse('accounts:login'))
    return render(request, 'blog/blog-single.html', context)

def blog_search(request):
    query = request.GET.get('s')
    posts = Post.objects.filter(published_date__lte=timezone.now(), status=1)
    if query:
        posts = posts.filter(content__contains=query)
    context = {'posts': posts}
    return render(request, 'blog/blog-home.html', context)


# def blog_category(request, category_name):
#     posts = Post.objects.filter(published_date__lte=timezone.now(), status=1)
#     posts = posts.filter(category__name=category_name)
#     context = {'posts': posts}
#     return render(request, 'blog/blog-home.html', context)

templates/blog/blog-ads-widget.html
{% load static %}
<div class="single-sidebar-widget ads-widget">
    <a href="#"
      ><img
        class="img-fluid"
        src="{% static 'img/blog/ads-banner.jpg' %}"
        alt=""
    /></a>
  </div>

templates/blog/blog-ads.html
{% load static %}
<div class="single-sidebar-widget ads-widget">
    <a href="#"
      ><img
        class="img-fluid"
        src="{% static 'img/blog/ads-banner.jpg' %}"
        alt=""
    /></a>
  </div>

templates/blog/blog-category-widget.html
{% load static %}
<div class="single-sidebar-widget post-category-widget">
    <h4 class="category-title">Post Catgories</h4>
    <ul class="cat-list">
      {% for name,count in categories.items %}
      <li>
        <a href="{% url 'blog:category' category_name=name %}" class="d-flex justify-content-between">
          <p>{{ name }}</p>
          <p>{{ count }}</p>
        </a>
      </li>
      {% endfor %}
    </ul>
  </div>

templates/blog/blog-home.html
{% extends 'base.html' %} {% load static %} {% load blog_tags %} {% block content %}
<!-- start banner Area -->
<section class="banner-area relative blog-home-banner" id="home">
  <div class="overlay overlay-bg"></div>
  <div class="container">
    <div class="row d-flex align-items-center justify-content-center">
      <div class="about-content blog-header-content col-lg-12">
        <h1 class="text-white">Dude You’re Getting a Telescope</h1>
        <p class="text-white">
          There is a moment in the life of any aspiring astronomer that it is
          time to buy that first
        </p>
      </div>
    </div>
  </div>
</section>
<!-- End banner Area -->

<!-- Start top-category-widget Area -->
<section class="top-category-widget-area pt-90 pb-90">
  <div class="container">
    <div class="row">
      <div class="col-lg-4">
        <div class="single-cat-widget">
          <div class="content relative">
            <div class="overlay overlay-bg"></div>
            <a href="#" target="_blank">
              <div class="thumb">
                <img
                  class="content-image img-fluid d-block mx-auto"
                  src="{% static 'img/blog/cat-widget1.jpg' %}"
                  alt=""
                />
              </div>
              <div class="content-details">
                <h4 class="content-title mx-auto text-uppercase">
                  Social life
                </h4>
                <span></span>
                <p>Enjoy your social life together</p>
              </div>
            </a>
          </div>
        </div>
      </div>
      <div class="col-lg-4">
        <div class="single-cat-widget">
          <div class="content relative">
            <div class="overlay overlay-bg"></div>
            <a href="#" target="_blank">
              <div class="thumb">
                <img
                  class="content-image img-fluid d-block mx-auto"
                  src="{% static 'img/blog/cat-widget2.jpg' %}"
                  alt=""
                />
              </div>
              <div class="content-details">
                <h4 class="content-title mx-auto text-uppercase">Politics</h4>
                <span></span>
                <p>Be a part of politics</p>
              </div>
            </a>
          </div>
        </div>
      </div>
      <div class="col-lg-4">
        <div class="single-cat-widget">
          <div class="content relative">
            <div class="overlay overlay-bg"></div>
            <a href="#" target="_blank">
              <div class="thumb">
                <img
                  class="content-image img-fluid d-block mx-auto"
                  src="{% static 'img/blog/cat-widget3.jpg' %}"
                  alt=""
                />
              </div>
              <div class="content-details">
                <h4 class="content-title mx-auto text-uppercase">Food</h4>
                <span></span>
                <p>Let the food be finished</p>
              </div>
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- End top-category-widget Area -->

<!-- Start post-content Area -->
<section class="post-content-area">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 posts-list">
        {% for post in posts %}
        <div class="single-post row">
          <div class="col-lg-3 col-md-3 meta-details">
            <ul class="tags">
              {% for category in post.category.all %}
              <li><a href="{% url 'blog:category' category_name=category.name %}">{{ category }}</a>{% if not forloop.last %},{% endif %}</li>
              {% endfor %}
            </ul>
            <div class="user-details row">
              <p class="user-name col-lg-12 col-md-12 col-6">
                <a href="{% url 'blog:author' author_username=post.author.username %}">{{ post.author }}</a> <span class="lnr lnr-user"></span>
              </p>
              <p class="date col-lg-12 col-md-12 col-6">
                <a href="#">{{ post.created_date|date:"D d M Y" }}</a>
                <span class="lnr lnr-calendar-full"></span>
              </p>
              <p class="view col-lg-12 col-md-12 col-6">
                <a href="#">{{ post.counted_views }} Views</a> <span class="lnr lnr-eye"></span>
              </p>
              <p class="comments col-lg-12 col-md-12 col-6">
                <a href="#">06 Comments</a> <span class="lnr lnr-bubble"></span>
              </p>
            </div>
          </div>
          <div class="col-lg-9 col-md-9">
            <div class="feature-img">
              <img
                class="img-fluid"
                src="{{ post.image.url }}"
                alt=""
              />
            </div>
            <a class="posts-title" href="{% url 'blog:single' pid=post.id %}"
              ><h3>{{ post.title }}</h3></a
            >
            <p class="excert">
              {{ post.content|truncatewords:21|safe }}
            </p>
            <a href="{% url 'blog:single' pid=post.id %}" class="primary-btn">View More</a>
          </div>
        </div>
        {% endfor %}
        <nav class="blog-pagination justify-content-center d-flex">
          <ul class="pagination">
            <li class="page-item">
              {% if posts.has_previous %}
              <a href="?page={{posts.previous_page_number}}" class="page-link" aria-label="Previous">
                <span aria-hidden="true">
                  <span class="lnr lnr-chevron-left"></span>
                </span>
              </a>
              {% endif %}
            </li>
            {% for page in posts.paginator.page_range %}
              {% if posts.number == page %}
                <li class="page-item active"><span class="page-link">{{page}}</span></li>
              {% else %}
                <li class="page-item"><a href="?page={{page}}" class="page-link">{{page}}</a></li>
                </li>
              {% endif %}
            {% endfor %}
            <li class="page-item">
              {% if posts.has_next %}
              <a href="?page={{posts.next_page_number}}" class="page-link" aria-label="Next">
                <span aria-hidden="true">
                  <span class="lnr lnr-chevron-right"></span>
                </span>
              </a>
              {% endif %}
            </li>
          </ul>
        </nav>
      </div>
      <div class="col-lg-4 sidebar-widgets">
        <div class="widget-wrap">
          {% include 'blog/blog-search-widget.html' %}

          {% include 'blog/blog-writer-widget.html' %}

          {% comment %} removed popular posts widget {% endcomment %}

          {% include 'blog/blog-ads-widget.html' %}

          {% categories_widget %}

          {% include 'blog/blog-newsletter-widget.html' %}

          {% include 'blog/blog-tag-widget.html' %}

        </div>
      </div>
    </div>
  </div>
</section>
<!-- End post-content Area -->
{% endblock content %}

templates/blog/blog-newsletter-widget.html
{% load static %}
<div class="single-sidebar-widget newsletter-widget">
    <h4 class="newsletter-title">Newsletter</h4>
    <p>
      Here, I focus on a range of items and features that we use in life
      without giving them a second thought.
    </p>
    <div class="form-group d-flex flex-row">
      <div class="col-autos">
        <div class="input-group">
          <div class="input-group-prepend">
            <div class="input-group-text">
              <i class="fa fa-envelope" aria-hidden="true"></i>
            </div>
          </div>
          <input
            type="text"
            class="form-control"
            id="inlineFormInputGroup"
            placeholder="Enter email"
            onfocus="this.placeholder = ''"
            onblur="this.placeholder = 'Enter email'"
          />
        </div>
      </div>
      <a href="#" class="bbtns">Subcribe</a>
    </div>
    <p class="text-bottom">You can unsubscribe at any time</p>
  </div>

templates/blog/blog-popular-widget.html
{% load static %} {% load humanize %}
<div class="single-sidebar-widget popular-post-widget">
    <h4 class="popular-title">Popular Posts</h4>
    {% for post in posts %}
    <div class="popular-post-list">
      <div class="single-post-list d-flex flex-row align-items-center">
        <div class="thumb">
          <img
            class="img-fluid"
            src="{{ post.image.url }}"
            alt=""
          />
        </div>
        <div class="details">
          <a href="{% url 'blog:single' pid=post.id %}"
            ><h6>{{ post.title }}</h6></a
          >
          <p>{{ post.published_date|naturaltime }}</p>
        </div>
      </div>
      {% endfor %}
    </div>
</div>

templates/blog/blog-search-widget.html
{% load static %}
<div class="single-sidebar-widget search-widget">
    <form class="search-form" action="{% url 'blog:search' %}" method="get">
      <input
        placeholder="Search Posts"
        name="s"
        type="text"
        onfocus="this.placeholder = ''"
        onblur="this.placeholder = 'Search Posts'"
      />
      <button type="submit"><i class="fa fa-search"></i></button>
    </form>
  </div>

templates/blog/blog-tag-widget.html
{% load static %}
<div class="single-sidebar-widget tag-cloud-widget">
    <h4 class="tagcloud-title">Tag Clouds</h4>
    <ul>
      {% for tag in post.tag.all %}
      <li>
        <a href="{% url 'blog:tag' tag_name=tag.name %}">
          {{ tag.name }}
        </a>
      </li>
      {% endfor %}
    </ul>
  </div>

templates/blog/blog-writer-widegt.html
{% load static %}
<div class="single-sidebar-widget user-info-widget">
    <img src="{% static 'img/blog/user-info.png' %}" alt="" />
    <a href="#"><h4>Charlie Barber</h4></a>
    <p>Senior blog writer</p>
    <ul class="social-links">
      <li>
        <a href="#"><i class="fa fa-facebook"></i></a>
      </li>
      <li>
        <a href="#"><i class="fa fa-twitter"></i></a>
      </li>
      <li>
        <a href="#"><i class="fa fa-github"></i></a>
      </li>
      <li>
        <a href="#"><i class="fa fa-behance"></i></a>
      </li>
    </ul>
    <p>
      Boot camps have its supporters andit sdetractors. Some people do
      not understand why you should have to spend money on boot camp
      when you can get. Boot camps have itssuppor ters andits
      detractors.
    </p>
  </div>

templates/blog/blog-writer-widget.html
{% load static %}
<div class="single-sidebar-widget user-info-widget">
    <img src="{% static 'img/blog/user-info.png' %}" alt="" />
    <a href="#"><h4>Big Author</h4></a>
    <p>Senior blog writer</p>
    <ul class="social-links">
      <li>
        <a href="#"><i class="fa fa-facebook"></i></a>
      </li>
      <li>
        <a href="#"><i class="fa fa-twitter"></i></a>
      </li>
      <li>
        <a href="#"><i class="fa fa-github"></i></a>
      </li>
      <li>
        <a href="#"><i class="fa fa-behance"></i></a>
      </li>
    </ul>
    <p>
      Boot camps have its supporters andit sdetractors. Some people do
      not understand why you should have to spend money on boot camp
      when you can get. Boot camps have itssuppor ters andits
      detractors.
    </p>
  </div>