accounts/urls.py
from django.urls import path
from accounts.views import login_view, logout_view, register_view, ResetPasswordView #, profile_view, profile_edit_view,
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy

app_name = 'accounts'

urlpatterns = [
    path('login', login_view, name='login'),
     path('logout', logout_view, name='logout'),
     path('register', register_view, name='register'),
    path('password-reset', ResetPasswordView.as_view(), name='password_reset'),
    path('password-reset-confirm/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(template_name='accounts/password_reset_confirm.html',
                                                    success_url=reverse_lazy('accounts:password_reset_complete')),
         name='password_reset_confirm'),
    path('password-reset-complete/',
        auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'),
        name='password_reset_complete'),
    # path('profile', profile_view, name='profile'),
    # path('profile/edit', profile_edit_view, name='profile-edit'),
]

blog/urls.py
from django.urls import path
from .views import blog_view, blog_single, blog_search #,blog_category
from blog.feeds import LatestEntriesFeed

app_name = 'blog'

urlpatterns = [
    path('', blog_view, name='index'),
    path('<int:pid>', blog_single, name='single'),
    path('author/<author_username>', blog_view, name='author'),
    path('search/', blog_search, name='search'),
    path('tag/<str:tag_name>', blog_view, name='tag'),
    path("rss/feed/", LatestEntriesFeed()),
    path('category/<str:category_name>', blog_view, name='category'),
]

django_website_example/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from blog.sitemaps import BlogSitemap
from django.contrib.sitemaps.views import sitemap
from testing.sitemaps import StaticViewSitemap
from debug_toolbar.toolbar import debug_toolbar_urls

sitemaps = {
    'static': StaticViewSitemap,
    'blog': BlogSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('testing.urls')),
    path('accounts/', include('accounts.urls')),
    path('blog/', include('blog.urls')),
    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
    path('robots.txt', include('robots.urls')),
    path('tinymce/', include('tinymce.urls')),
    path('captcha/', include('captcha.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += debug_toolbar_urls()

testing/urls.py
from django.urls import path
from testing.views import index_view, about_view, contact_view, form_test_view, newsletter_view


app_name = 'testing'

urlpatterns = [
    path('', index_view, name='index'),
    path('about', about_view, name='about'),
    path('contact', contact_view, name='contact'),
    path('form-test', form_test_view, name='form-test'),
    path('newsletter', newsletter_view, name='newsletter'),
    ]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="zxx" class="no-js">
  <head>
    <!-- Mobile Specific Meta -->
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <!-- Favicon-->
    <link rel="shortcut icon" href="{% static 'img/i2.jpg' %}" />
    <!-- Author Meta -->
    <meta name="author" content="colorlib" />
    <!-- Meta Description -->
    <meta name="description" content="" />
    <!-- Meta Keyword -->
    <meta name="keywords" content="" />
    <!-- meta character set -->
    <meta charset="UTF-8" />
    <!-- Site Title -->
    <title>Travel</title>

    <link
      href="https://fonts.googleapis.com/css?family=Poppins:100,200,400,300,500,600,700"
      rel="stylesheet"
    />
    <!--
        CSS
        ============================================= -->
    <link rel="stylesheet" href="{% static 'css/linearicons.css'%}" />
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css'%}" />
    <link rel="stylesheet" href="{% static 'css/bootstrap.css'%}" />
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css'%}" />
    <link rel="stylesheet" href="{% static 'css/jquery-ui.css'%}" />
    <link rel="stylesheet" href="{% static 'css/nice-select.css'%}" />
    <link rel="stylesheet" href="{% static 'css/animate.min.css'%}" />
    <link rel="stylesheet" href="{% static 'css/owl.carousel.css'%}" />
    <link rel="stylesheet" href="{% static 'css/main.css'%}" />
  </head>
  <body>
    <header id="header">
      <div class="header-top">
        <div class="container">
          <div class="row align-items-center">
            <div class="col-lg-6 col-sm-6 col-6 header-top-left">
              <ul>
                {% if request.user.is_authenticated %}
                  <li>Logged in as {{ request.user.username }}</li>
                  <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
                {% elif not request.user.is_authenticated %}
                  <li><a href="{% url 'accounts:login' %}">Login</a></li>
                  <li><a href="{% url 'accounts:register' %}">Signup</a></li>
                {% endif %}
              </ul>
            </div>
            <div class="col-lg-6 col-sm-6 col-6 header-top-right">
              <div class="header-social">
                <a href="#"><i class="fa fa-facebook"></i></a>
                <a href="#"><i class="fa fa-twitter"></i></a>
                <a href="#"><i class="fa fa-dribbble"></i></a>
                <a href="#"><i class="fa fa-behance"></i></a>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="container main-menu">
        <div class="row align-items-center justify-content-between d-flex">
          <div id="logo">
            <a href="{% url 'testing:index' %}"
              ><img src="{% static 'img/logo.png' %}" alt="" title=""
            /></a>
          </div>
          <nav id="nav-menu-container">
            <ul class="nav-menu">
              <li><a href="{% url 'testing:index' %}">Home</a></li>
              <li><a href="{% url 'testing:about' %}">About</a></li>
              <li><a href="{% url 'blog:index' %}">Blog</a></li>
              </li>
              <li><a href="{% url 'testing:contact' %}">Contact</a></li>
            </ul>
          </nav>
          <!-- #nav-menu-container -->
        </div>
      </div>
    </header>
    <!-- #header -->
    {% block content %} 

    {% endblock content %}
    <!-- start footer Area -->
    <footer class="footer-area section-gap">
      <div class="container">
        <div class="row">
          <div class="col-lg-3 col-md-6 col-sm-6">
            <div class="single-footer-widget">
              <h6>About Agency</h6>
              <p>
                The world has become so fast paced that people don’t want to
                stand by reading a page of information, they would much rather
                look at a presentation and understand the message. It has come
                to a point
              </p>
            </div>
          </div>
          <div class="col-lg-3 col-md-6 col-sm-6">
            <div class="single-footer-widget">
              <h6>Navigation Links</h6>
              <div class="row">
                <div class="col">
                  <ul>
                    <li><a href="#">Home</a></li>
                    <li><a href="#">Feature</a></li>
                    <li><a href="#">Services</a></li>
                    <li><a href="#">Portfolio</a></li>
                  </ul>
                </div>
                <div class="col">
                  <ul>
                    <li><a href="#">Team</a></li>
                    <li><a href="#">Pricing</a></li>
                    <li><a href="#">Blog</a></li>
                    <li><a href="#">Contact</a></li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
          <div class="col-lg-3 col-md-6 col-sm-6">
            <div class="single-footer-widget">
              <h6>Newsletter</h6>
              <p>
                For business professionals caught between high OEM price and
                mediocre print and graphic output.
              </p>
              <div>
                <form
                  action="{% url 'testing:newsletter' %}"
                  method="post"
                  class="subscription relative"
                >
                {% csrf_token %}
                  <div class="input-group d-flex flex-row">
                    <input
                      name="email"
                      placeholder="Email Address"
                      onfocus="this.placeholder = ''"
                      onblur="this.placeholder = 'Email Address '"
                      required=""
                      type="email"
                    />
                    <button class="btn bb-btn" type="submit">
                      <span class="lnr lnr-location"></span>
                    </button>
                  </div>
                  <div class="mt-10 info"></div>
                </form>
              </div>
            </div>
          </div>
          <div class="col-lg-3 col-md-6 col-sm-6">
            <div class="single-footer-widget mail-chimp">
              <h6 class="mb-20">InstaFeed</h6>
              <ul class="instafeed d-flex flex-wrap">
                <li><img src="{% static 'img/i1.jpg' %}" alt="" /></li>
                <li><img src="{% static 'img/i2.jpg' %}" alt="" /></li>
                <li><img src="{% static 'img/i3.jpg' %}" alt="" /></li>
                <li><img src="{% static 'img/i4.jpg' %}" alt="" /></li>
                <li><img src="{% static 'img/i5.jpg' %}" alt="" /></li>
                <li><img src="{% static 'img/i6.jpg' %}" alt="" /></li>
                <li><img src="{% static 'img/i7.jpg' %}" alt="" /></li>
                <li><img src="{% static 'img/i8.jpg' %}" alt="" /></li>
              </ul>
            </div>
          </div>
        </div>

        <div
          class="row footer-bottom d-flex justify-content-between align-items-center"
        >
          <p class="col-lg-8 col-sm-12 footer-text m-0">
            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
            Copyright &copy;
            <script>
              document.write(new Date().getFullYear());
            </script>
            All rights reserved | This template is made with
            <i class="fa fa-heart-o" aria-hidden="true"></i> by
            <a href="https://colorlib.com" target="_blank">Colorlib</a>
            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
          </p>
          <div class="col-lg-4 col-sm-12 footer-social">
            <a href="#"><i class="fa fa-facebook"></i></a>
            <a href="#"><i class="fa fa-twitter"></i></a>
            <a href="#"><i class="fa fa-dribbble"></i></a>
            <a href="#"><i class="fa fa-behance"></i></a>
          </div>
        </div>
      </div>
    </footer>
    <!-- End footer Area -->
    {% if messages %}
          <ul class="messages">
            {% for message in messages %}
             {% if message.tags %} <script>alert('{{ message }}')</script>{% endif %}
            {% endfor %}
          </ul>
        {% endif %}
    <script src="{% static 'js/vendor/jquery-2.2.4.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/vendor/bootstrap.min.js' %}"></script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBhOdIF3Y9382fqJYt5I_sswSrEw5eihAA"></script>
    <script src="{% static 'js/jquery-ui.js' %}"></script>
    <script src="{% static 'js/easing.min.js' %}"></script>
    <script src="{% static 'js/hoverIntent.js' %}"></script>
    <script src="{% static 'js/superfish.min.js' %}"></script>
    <script src="{% static 'js/jquery.ajaxchimp.min.js' %}"></script>
    <script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
    <script src="{% static 'js/jquery.nice-select.min.js' %}"></script>
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/mail-script.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
  </body>
</html>